//! TheirStack Jobs API adapter (decision 0012, OpenSpec change
//! `theirstack-paid-feed`): a rich, paid source. Each record carries the full
//! description (markdown) plus structured salary/remote/technology fields, so
//! the adapter maps records directly to [`IngestOutcome`] — no re-fetch of the
//! canonical page (the snapshot path).

use std::{collections::BTreeMap, future::Future, pin::Pin, sync::LazyLock};

use miette::{Context, IntoDiagnostic, Result, bail};
use regex::Regex;
use serde_json::{Value, json};
use tracing::{debug, warn};
use url::Url;

use super::{DiscoverySource, SourceBatch};
use crate::{
    config::{Config, SourceConfig},
    domain::events::{CompRange, ExtractedFields},
    ingest::{self, Fetcher, HttpClient, IngestOutcome, PoliteClient},
};

const THEIRSTACK_API: &str = "https://api.theirstack.com/v1/jobs/search";
const THEIRSTACK_BALANCE_API: &str = "https://api.theirstack.com/v0/billing/credit-balance";
/// TheirStack's maximum page size (decision 0012).
const PAGE_SIZE: u64 = 500;

pub struct Theirstack {
    api_url: String,
    api_key: String,
    posted_at_max_age_days: u64,
    strict_filtering: bool,
    blacklist: Vec<String>,
    remote_only: bool,
    compensation_floor: Option<u64>,
    discovered_at_gte: Option<String>,
    /// Operator-declared query filters (`theirstack-spend-control`
    /// decision 1), validated at construction and merged into the request
    /// body by `build_query`.
    query: BTreeMap<String, Value>,
    /// Optional per-run spend bound (`theirstack-spend-control` decision 2).
    max_credits_per_run: Option<u64>,
}

/// Query keys the adapter itself generates — unconditional reserved
/// (`theirstack-spend-control` decision 1): pagination, the recency config,
/// the watermark cursor, and the blacklist pre-filter are budgeting
/// machinery, not operator surface.
const ALWAYS_RESERVED_QUERY_KEYS: &[&str] = &[
    "limit",
    "page",
    // TheirStack's alternative pagination parameter (the deferred
    // cursor-based pagination path): a fixed operator cursor alongside the
    // adapter's `page` counter would fetch ambiguous — potentially
    // duplicate — pages, the same class of silent budgeting breakage the
    // other keys are reserved against (PR #45 review).
    "cursor",
    "posted_at_max_age_days",
    "discovered_at_gte",
    "company_name_not",
    "company_domain_not",
];
/// Query keys generated by strict mode — reserved only when
/// `strict_filtering` is on. With strict mode off they are free operator
/// surface (e.g. `workplace_types_or = ["remote", "hybrid"]`, a shape
/// strict mode cannot express).
const STRICT_RESERVED_QUERY_KEYS: &[&str] = &["workplace_types_or", "min_salary_usd"];

impl Theirstack {
    pub fn new(
        source: &SourceConfig,
        config: &Config,
        discovered_at_gte: Option<String>,
    ) -> Result<Self> {
        let query = validate_query(source)?;
        Ok(Self {
            api_url: THEIRSTACK_API.into(),
            api_key: source.api_key.clone(),
            posted_at_max_age_days: source.posted_at_max_age_days,
            strict_filtering: source.strict_filtering,
            blacklist: config.blacklist.clone(),
            remote_only: config.remote_only,
            compensation_floor: config.compensation_floor,
            discovered_at_gte,
            query,
            max_credits_per_run: source.max_credits_per_run,
        })
    }

    /// Build the search query body (pure, testable — design decisions 3 & 4):
    /// blacklist → `company_name_not`/`company_domain_not`, recency →
    /// `posted_at_max_age_days` always, and behind `strict_filtering` also
    /// `remote_only` → `workplace_types_or: ["remote"]` and `compensation_floor`
    /// → `min_salary_usd`. The operator's `[sources.theirstack.query]` table
    /// rides along after the generated keys (reserved keys were rejected at
    /// construction, so the merge cannot collide). By default the adapter
    /// adds no filters of its own beyond blacklist + recency — skills are a
    /// score dimension, not a filter, unless the operator explicitly pays to
    /// narrow the feed (`theirstack-spend-control` supersedes that default
    /// rule for an explicit query table).
    fn build_query(&self) -> Value {
        let mut query = serde_json::Map::new();
        query.insert(
            "posted_at_max_age_days".into(),
            json!(self.posted_at_max_age_days),
        );
        query.insert("limit".into(), json!(PAGE_SIZE));

        // Best-effort server-side blacklist pre-filter (the client gate is the
        // backstop): domain-looking entries → `company_domain_not`, names →
        // `company_name_not` (exact, case-sensitive).
        let mut domains = Vec::new();
        let mut names = Vec::new();
        for entry in &self.blacklist {
            if entry.contains('.') && !entry.chars().any(char::is_whitespace) {
                domains.push(Value::String(entry.clone()));
            } else {
                names.push(Value::String(entry.clone()));
            }
        }
        if !domains.is_empty() {
            query.insert("company_domain_not".into(), Value::Array(domains));
        }
        if !names.is_empty() {
            query.insert("company_name_not".into(), Value::Array(names));
        }

        if self.strict_filtering {
            if self.remote_only {
                query.insert("workplace_types_or".into(), json!(["remote"]));
            }
            if let Some(floor) = self.compensation_floor {
                query.insert("min_salary_usd".into(), json!(floor));
            }
        }

        if let Some(watermark) = &self.discovered_at_gte {
            query.insert("discovered_at_gte".into(), json!(watermark));
        }

        for (key, value) in &self.query {
            query.insert(key.clone(), value.clone());
        }

        Value::Object(query)
    }

    /// Parse a search response into jobs plus the truncation count.
    fn parse_response(value: &Value) -> Result<TheirstackResponse> {
        let data = value.get("data").and_then(Value::as_array).ok_or_else(|| {
            miette::miette!("theirstack response missing data array (shape changed?)")
        })?;
        let jobs = data.iter().map(parse_job).collect();
        let truncated_results = value
            .get("metadata")
            .and_then(|m| m.get("truncated_results"))
            .and_then(num_to_u64)
            .unwrap_or(0);
        Ok(TheirstackResponse {
            jobs,
            truncated_results,
        })
    }
}

/// One parsed TheirStack record, before mapping to [`IngestOutcome`].
#[derive(Clone, Debug)]
struct TheirstackJob {
    url: Option<String>,
    description: String,
    title: Option<String>,
    company: Option<String>,
    location: Option<String>,
    comp: Option<CompRange>,
    remote: Option<bool>,
    /// Parsed for observability and the eventual skills-scoring enrichment;
    /// the v0 skills dimension still matches resume keywords against
    /// `raw_text`, so this is not yet consumed (asserted by tests).
    #[allow(dead_code)]
    technology_slugs: Vec<String>,
    discovered_at: Option<String>,
}

#[derive(Debug)]
struct TheirstackResponse {
    jobs: Vec<TheirstackJob>,
    truncated_results: u64,
}

impl TheirstackJob {
    fn into_outcome(self) -> IngestOutcome {
        IngestOutcome {
            adapter: "theirstack".into(),
            source: "theirstack".into(),
            url: self.url,
            raw_text: self.description,
            extracted: ExtractedFields {
                title: self.title,
                company: self.company,
                location: self.location,
                remote: self.remote,
                comp: self.comp,
                ..Default::default()
            },
        }
    }
}

impl DiscoverySource for Theirstack {
    fn fetch<'a>(
        &'a self,
        client: &'a HttpClient,
    ) -> Pin<Box<dyn Future<Output = Result<SourceBatch>> + Send + 'a>> {
        Box::pin(async move {
            // A missing key fails the source (reported; run continues), never
            // a silent skip.
            if self.api_key.is_empty() {
                bail!(
                    "theirstack api_key is empty (set THEIRSTACK_API_KEY or [sources.theirstack].api_key)"
                );
            }
            let query = self.build_query();
            let api_url = Url::parse(&self.api_url).expect("static API URL parses");
            let balance_url =
                Url::parse(THEIRSTACK_BALANCE_API).expect("static balance URL parses");
            let fetched = fetch_jobs(
                client,
                &api_url,
                &query,
                &self.api_key,
                &balance_url,
                self.max_credits_per_run,
            )
            .await?;
            let discovered_at = max_discovered_at(&fetched.jobs);
            let mut outcomes = Vec::with_capacity(fetched.jobs.len());
            for job in fetched.jobs {
                emit_mismatches(&job);
                outcomes.push(job.into_outcome());
            }
            Ok(SourceBatch {
                outcomes,
                failed: 0,
                truncated_results: fetched.truncated_results,
                discovered_at,
                partial_error: fetched.partial_error,
                credits_spent: fetched.credits_spent,
            })
        })
    }

    fn charges_per_record(&self) -> bool {
        true
    }
}

/// The outcome of a paginated fetch: the jobs (possibly partial), the
/// credit-exhaustion count, the credits actually spent (records returned),
/// and — when the fetch ended early after records were already paid for —
/// why it ended (design decision 8).
#[derive(Debug, Default)]
struct FetchedJobs {
    jobs: Vec<TheirstackJob>,
    truncated_results: u64,
    credits_spent: u64,
    partial_error: Option<String>,
}

/// Validate the operator's `[sources.theirstack.query]` table
/// (`theirstack-spend-control` decision 1). Runs at adapter construction —
/// inside `build_sources` — so a bad table fails the run before any network
/// I/O and no credits are spent. Values are converted to JSON eagerly so
/// the error for an unconvertible shape (a TOML datetime) also lands here.
fn validate_query(source: &SourceConfig) -> Result<BTreeMap<String, Value>> {
    let mut out = BTreeMap::new();
    let Some(query) = &source.query else {
        return Ok(out);
    };
    for (key, value) in query {
        if ALWAYS_RESERVED_QUERY_KEYS.contains(&key.as_str()) {
            bail!(
                "[sources.theirstack.query]: '{key}' is reserved — the adapter owns \
                 pagination, recency, the watermark cursor, and the blacklist pre-filter"
            );
        }
        if source.strict_filtering && STRICT_RESERVED_QUERY_KEYS.contains(&key.as_str()) {
            bail!(
                "[sources.theirstack.query]: '{key}' collides with strict_filtering \
                 (which generates it) — remove the key or disable strict mode"
            );
        }
        let value = serde_json::to_value(value)
            .into_diagnostic()
            .wrap_err_with(|| format!("[sources.theirstack.query]: '{key}'"))?;
        out.insert(key.clone(), value);
    }
    Ok(out)
}

/// The account's remaining API credits, from the free credit-balance
/// endpoint (live shape: `{"api_credits":1700,"used_api_credits":1501,…}`).
/// One credit per record, so `remaining` is exactly how many more records
/// the account can pay for.
async fn credit_balance<F: Fetcher>(
    client: &PoliteClient<F>,
    balance_url: &Url,
    api_key: &str,
) -> Result<u64> {
    let value = client.get_json_auth(balance_url, Some(api_key)).await?;
    let total = value
        .get("api_credits")
        .and_then(num_to_u64)
        .ok_or_else(|| miette::miette!("credit balance response missing api_credits"))?;
    let used = value
        .get("used_api_credits")
        .and_then(num_to_u64)
        .unwrap_or(0);
    Ok(total.saturating_sub(used))
}

/// Why a page request failed. A payment-required (402) response is a
/// known credit-exhaustion signal at ANY page — a reported shortfall, not
/// a generic fetch failure — so it salvages even with no records fetched
/// (page 0), preserving the unreturned count as truncation (review of
/// PR #44: the old page-0 `bail!` discarded it).
#[derive(Debug)]
enum PageFailure {
    Fetch { reason: String },
    PaymentRequired { reason: String },
}

impl PageFailure {
    fn fetch(reason: String) -> Self {
        PageFailure::Fetch { reason }
    }

    fn payment_required(reason: String) -> Self {
        PageFailure::PaymentRequired { reason }
    }
}

/// Paginate the search endpoint (serial, `page`-based), bounded by the
/// credit balance and the optional per-run budget (`theirstack-spend-control`
/// decision 2). Generic over the transport seam so tests can script the
/// responses. Per page: check the balance, cap the page `limit` to what the
/// balance (and budget) can pay for, request, and stop as a partial fetch —
/// records kept, reason carried — when the balance or budget runs out. A
/// non-payment failure AFTER records have been fetched salvages them
/// (design decision 8); before any record is fetched it is a hard `Err`
/// (the whole-source failure contract). A payment-required (402) response
/// is exhaustion at ANY page and returns a partial batch (possibly empty)
/// so the unreturned count is never discarded.
#[allow(clippy::too_many_arguments)]
async fn fetch_jobs<F: Fetcher>(
    client: &PoliteClient<F>,
    api_url: &Url,
    query: &Value,
    api_key: &str,
    balance_url: &Url,
    max_credits_per_run: Option<u64>,
) -> Result<FetchedJobs> {
    let mut fetched = FetchedJobs::default();
    let mut page = 0u64;
    loop {
        // Budget pass 1 — the account balance (a free endpoint check).
        // A failed check does NOT block the fetch: warn and proceed
        // uncapped; the 402 path and the salvage are the backstop.
        let balance = match credit_balance(client, balance_url, api_key).await {
            Ok(remaining) => Some(remaining),
            Err(err) => {
                warn!(
                    error = %err,
                    "credit balance check failed; proceeding uncapped"
                );
                None
            }
        };
        let mut page_limit = PAGE_SIZE;
        if let Some(remaining) = balance {
            if remaining == 0 {
                // Nothing fetched yet: the whole-source failure contract
                // (no records, source reported failed, run continues).
                if fetched.jobs.is_empty() {
                    bail!("credit balance exhausted (0 remaining)");
                }
                // Mid-run with a drained balance: do NOT declare
                // exhaustion blindly — the result set may have ended
                // exactly at the last capped page (the false-partial bug
                // the budget-loop proptest caught: a complete fetch
                // reported as failed). Ask anyway: free either way. If
                // matches remain, the API 402s and the payment-required
                // path reports the shortfall WITH its count; if none
                // remain, the empty page completes the fetch cleanly.
                // Leave the page uncapped — the API arbitrates.
            } else {
                page_limit = page_limit.min(remaining);
            }
        }
        // Budget pass 2 — the per-run spend bound, if declared.
        if let Some(budget) = max_credits_per_run {
            let left = budget.saturating_sub(fetched.credits_spent);
            if left == 0 {
                let reason = format!(
                    "per-run credit budget of {budget} reached ({} spent)",
                    fetched.credits_spent
                );
                if fetched.jobs.is_empty() {
                    bail!("{reason}");
                }
                fetched.partial_error = Some(reason);
                return Ok(fetched);
            }
            page_limit = page_limit.min(left);
        }
        debug!(
            page,
            page_limit,
            balance = ?balance,
            spent = fetched.credits_spent,
            "theirstack page budget check"
        );

        let mut page_query = query.clone();
        if let Value::Object(ref mut map) = page_query {
            map.insert("page".into(), json!(page));
            map.insert("limit".into(), json!(page_limit));
        }
        // One page: 2xx parses; every other outcome becomes a reason
        // string. The 402 body is mined BEFORE the salvage decision — its
        // "Required: N API credits" is the unreturned-record count the
        // credit-exhaustion contract needs.
        let step: std::result::Result<TheirstackResponse, PageFailure> = match client
            .post_json_status(api_url, &page_query, Some(api_key))
            .await
        {
            Ok((status, value)) if (200..300).contains(&status) => match value {
                Some(value) => Theirstack::parse_response(&value).map_err(|e| {
                    PageFailure::fetch(format!("parsing theirstack page {page} response: {e}"))
                }),
                None => Err(PageFailure::fetch(format!(
                    "theirstack page {page}: response body is not valid JSON"
                ))),
            },
            Ok((status, value)) => {
                let mut reason = format!("fetching {api_url} failed with status {status}");
                if let Some(detail) = value
                    .as_ref()
                    .and_then(|v| v.get("error"))
                    .and_then(|e| e.get("description"))
                    .and_then(Value::as_str)
                {
                    reason.push_str(&format!(": {detail}"));
                }
                if status == 402 {
                    // The "Required: N API credits" clause is a LOWER BOUND
                    // on the unreturned tail: it is the rejected page's own
                    // requirement, min(limit, remaining matches), not the
                    // whole tail (PR #44 review). Counted before the
                    // salvage decision so it survives even a page-0 402.
                    let unreturned = unreturned_from_402(value.as_ref());
                    fetched.truncated_results += unreturned;
                    Err(PageFailure::payment_required(reason))
                } else {
                    Err(PageFailure::fetch(reason))
                }
            }
            Err(err) => Err(PageFailure::fetch(err.to_string())),
        };
        match step {
            Ok(parsed) => {
                fetched.truncated_results = fetched.truncated_results.max(parsed.truncated_results);
                let count = parsed.jobs.len() as u64;
                fetched.credits_spent += count;
                fetched.jobs.extend(parsed.jobs);
                // A short page (fewer than its own capped limit) is the end
                // of the result set. A full capped page continues — the
                // next iteration's balance/budget check decides whether
                // more is payable, and stops with a reason if not.
                if count < page_limit {
                    return Ok(fetched);
                }
                page += 1;
            }
            // Exhaustion at ANY page — including page 0 — keeps the
            // unreturned count and returns a partial batch (possibly empty):
            // the driver lists the source as failed with this reason either
            // way, and the count is never discarded.
            Err(PageFailure::PaymentRequired { reason }) => {
                fetched.partial_error = Some(reason);
                return Ok(fetched);
            }
            // A non-payment failure before any record is fetched stays a
            // hard whole-source `Err`; after records, salvage.
            Err(PageFailure::Fetch { reason }) => {
                if fetched.jobs.is_empty() {
                    bail!("{reason}");
                }
                fetched.partial_error = Some(reason);
                return Ok(fetched);
            }
        }
    }
}

/// TheirStack's 402 credit-exhaustion body states how many credits the
/// rejected page required — one credit per record, so that number is a
/// LOWER BOUND on the unreturned records (it is `min(limit, remaining
/// matches)`, the rejected page's own requirement, not the whole tail;
/// the tail would need `include_total_results`, which stays off).
/// Live-verified 2026-10-07, GWLJ-2yflze. Best-effort: any shape change
/// just yields 0, and the failure reason string still carries the full
/// error text.
fn unreturned_from_402(value: Option<&Value>) -> u64 {
    let description = value
        .and_then(|v| v.get("error"))
        .and_then(|e| e.get("description"))
        .and_then(Value::as_str)
        .unwrap_or_default();
    // Live body: "...Required: 301 API credits. You currently have 199 API
    // credits. You need 301 more API credits."
    static REQUIRED_RE: LazyLock<Regex> = LazyLock::new(|| {
        Regex::new(r"Required: (\d+) API credits").expect("static regex compiles")
    });
    REQUIRED_RE
        .captures(description)
        .and_then(|caps| caps[1].parse().ok())
        .unwrap_or(0)
}

fn parse_job(record: &Value) -> TheirstackJob {
    let description = record
        .get("description")
        .and_then(Value::as_str)
        .unwrap_or_default()
        .to_string();
    let title = record
        .get("job_title")
        .and_then(Value::as_str)
        .map(str::to_string);
    let company = record
        .get("company")
        .and_then(Value::as_str)
        .map(str::to_string)
        .or_else(|| {
            record
                .get("company_object")
                .and_then(|o| o.get("name"))
                .and_then(Value::as_str)
                .map(str::to_string)
        });
    let location = record
        .get("location")
        .and_then(Value::as_str)
        .map(str::to_string);
    let technology_slugs = record
        .get("technology_slugs")
        .and_then(Value::as_array)
        .map(|arr| {
            arr.iter()
                .filter_map(Value::as_str)
                .map(str::to_string)
                .collect()
        })
        .unwrap_or_default();

    TheirstackJob {
        url: record
            .get("final_url")
            .and_then(Value::as_str)
            .or_else(|| record.get("url").and_then(Value::as_str))
            .and_then(|u| Url::parse(u).ok())
            .map(|u| crate::domain::identity::canonicalize_url(&u)),
        description,
        title,
        company,
        location,
        comp: parse_comp(record),
        remote: parse_remote(record),
        technology_slugs,
        discovered_at: record
            .get("discovered_at")
            .and_then(Value::as_str)
            .map(str::to_string),
    }
}

/// Map TheirStack's compensation fields to a [`CompRange`]. The pipeline's
/// contract is explicit that `CompRange` is USD/year (`gates.rs`,
/// `extract.rs`), and v0 has no currency conversion — so ONLY the `_usd`
/// fields are used, with `currency: "USD"`. A posting whose only salary data
/// is in a non-USD currency (or absent) maps to `None`: unknown compensation
/// passes the permissive floor gate rather than false-rejecting a £150k
/// posting against a $180k floor (the invisible loss the permissive-gate
/// spec forbids).
fn parse_comp(record: &Value) -> Option<CompRange> {
    let min = record.get("min_annual_salary_usd").and_then(num_to_u64);
    let max = record.get("max_annual_salary_usd").and_then(num_to_u64);
    if min.is_none() && max.is_none() {
        return None;
    }
    Some(CompRange {
        min,
        max,
        currency: "USD".into(),
        period: "year".into(),
        raw: record
            .get("salary_string")
            .and_then(Value::as_str)
            .unwrap_or_default()
            .to_string(),
    })
}

fn parse_remote(record: &Value) -> Option<bool> {
    let remote = record.get("remote").and_then(Value::as_bool);
    let hybrid = record.get("hybrid").and_then(Value::as_bool);
    match (remote, hybrid) {
        (Some(true), _) => Some(true),
        (_, Some(true)) => Some(false), // hybrid is confident non-remote
        (Some(false), _) => Some(false), // explicitly not remote
        _ => None,
    }
}

/// A number field, tolerant of floats that represent whole dollars.
fn num_to_u64(value: &Value) -> Option<u64> {
    value
        .as_u64()
        .or_else(|| value.as_f64().map(|f| f.round() as u64))
}

/// One field where TheirStack's structured data disagrees with our text
/// heuristics.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum MismatchField {
    Comp,
    Remote,
}

/// Trust-but-verify (design decision 2): run our own text heuristics over the
/// description and compare them against TheirStack's structured fields, in
/// BOTH directions — a structured field the description contradicts, or a
/// structured field TheirStack omitted but the description quotes (the latter
/// means ingest would store "unknown" while discarding extractable data).
/// Never blocking — it exists to make TheirStack data problems visible.
fn mismatches(job: &TheirstackJob, ours: &ExtractedFields) -> Vec<MismatchField> {
    let mut out = Vec::new();
    if comp_disagrees(ours.comp.as_ref(), job.comp.as_ref()) {
        out.push(MismatchField::Comp);
    }
    if ours.remote != job.remote {
        out.push(MismatchField::Remote);
    }
    out
}

/// Whether two compensation ranges disagree on the *semantic* fields
/// (`min`, `max`, `currency`, `period`). `raw` is deliberately ignored: it is
/// a presentation string from two independent sources (our regex capture vs
/// TheirStack's `salary_string`), so it differs on almost every posting even
/// when the numbers agree — comparing it would make every comp-carrying
/// posting a phantom "mismatch" and the signal would detect nothing. A
/// `None` on one side and `Some` on the other is a real disagreement.
fn comp_disagrees(a: Option<&CompRange>, b: Option<&CompRange>) -> bool {
    match (a, b) {
        (Some(a), Some(b)) => {
            a.min != b.min || a.max != b.max || a.currency != b.currency || a.period != b.period
        }
        (None, None) => false,
        _ => true,
    }
}

/// Emit one span per mismatch carrying the structured-vs-extracted values
/// (design decision 2: `comp_structured` vs `comp_extracted`, …), keyed by
/// url and source — the lead id is not minted until ingest, and the
/// canonicalized url is the deterministic join key in Honeycomb. Never
/// blocking.
fn emit_mismatches(job: &TheirstackJob) {
    let ours = ingest::extract::extract_fields(&job.description, job.location.as_deref());
    for field in mismatches(job, &ours) {
        let span = tracing::info_span!(
            "theirstack_mismatch",
            source = "theirstack",
            url = ?job.url,
            comp_structured = tracing::field::Empty,
            comp_extracted = tracing::field::Empty,
            remote_structured = tracing::field::Empty,
            remote_extracted = tracing::field::Empty,
        );
        match field {
            MismatchField::Comp => {
                span.record("comp_structured", tracing::field::debug(&job.comp));
                span.record("comp_extracted", tracing::field::debug(&ours.comp));
                debug!(
                    parent: &span,
                    field = "comp",
                    "theirstack structured comp disagrees with text heuristics"
                );
            }
            MismatchField::Remote => {
                span.record("remote_structured", tracing::field::debug(&job.remote));
                span.record("remote_extracted", tracing::field::debug(&ours.remote));
                debug!(
                    parent: &span,
                    field = "remote",
                    "theirstack structured remote disagrees with text heuristics"
                );
            }
        }
    }
}

/// Normalize TheirStack's `discovered_at` to a canonical UTC timestamp for
/// the watermark. The API emits naive UTC stamps (second precision), but we
/// also accept explicit offsets (`Z`, `+HH:MM`, `-HH:MM`) and render
/// everything to a uniform `YYYY-MM-DDTHH:MM:SSZ`. Uniform second precision
/// is what makes the lexicographic-max in [`max_discovered_at`] correct, and
/// the cursor we send back matches the API's own stamp shape.
fn normalize_discovered_at(raw: &str) -> String {
    let raw = raw.trim();
    // Explicit offset: parse as an absolute instant and render Zulu time.
    if let Ok(ts) = raw.parse::<jiff::Timestamp>() {
        return format!("{ts:.0}");
    }
    // Naive stamp (the API's documented shape): treat as UTC.
    if let Ok(dt) = raw.parse::<jiff::civil::DateTime>()
        && let Ok(zoned) = dt.to_zoned(jiff::tz::TimeZone::UTC)
    {
        return format!("{:.0}", zoned.timestamp());
    }
    // Unknown shape: pass through unchanged rather than corrupt it.
    raw.to_string()
}

/// The max `discovered_at` across a fetch (the watermark cursor's lower
/// bound for the next run). Normalized strings are same-precision RFC 3339,
/// so lexicographic order is chronological order.
fn max_discovered_at(jobs: &[TheirstackJob]) -> Option<String> {
    jobs.iter()
        .filter_map(|j| j.discovered_at.as_deref())
        .map(normalize_discovered_at)
        .max()
}

#[cfg(test)]
mod tests {
    use std::{
        collections::VecDeque,
        sync::{Arc, Mutex},
    };

    use proptest::prelude::*;
    use tracing_subscriber::layer::SubscriberExt;

    use super::*;
    use crate::ingest::FetchResponse;

    fn source_config(api_key: &str) -> SourceConfig {
        SourceConfig {
            enabled: true,
            api_key: api_key.into(),
            ..Default::default()
        }
    }

    fn config() -> Config {
        Config {
            blacklist: vec!["salesforce".into(), "google.com".into()],
            remote_only: true,
            compensation_floor: Some(180_000),
            ..Default::default()
        }
    }

    fn adapter(api_key: &str) -> Theirstack {
        Theirstack::new(&source_config(api_key), &config(), None).unwrap()
    }

    fn fixture_job() -> Value {
        serde_json::from_str(
            r#"{
                "job_title": "Senior Data Engineer",
                "description": "We are hiring a Senior Data Engineer. Remote. Salary: $200,000 - $250,000.",
                "company": "Acme",
                "company_domain": "acme.com",
                "final_url": "https://acme.com/careers/job/123?utm_source=x",
                "location": "Remote, US",
                "min_annual_salary_usd": 200000,
                "max_annual_salary_usd": 250000,
                "salary_currency": "USD",
                "salary_string": "$200,000 - $250,000",
                "remote": true,
                "technology_slugs": ["postgresql", "kafka"],
                "discovered_at": "2024-01-01T00:00:00"
            }"#,
        )
        .unwrap()
    }

    // ── query shaping (task 2.4) ─────────────────────────────────

    #[test]
    fn default_query_carries_blacklist_and_recency_only() {
        let query = adapter("k").build_query();
        assert_eq!(query["posted_at_max_age_days"], 30);
        assert_eq!(query["limit"], 500);
        // Domain-looking blacklist entry → company_domain_not; name → name.
        assert_eq!(query["company_domain_not"], json!(["google.com"]));
        assert_eq!(query["company_name_not"], json!(["salesforce"]));
        // Strict off: no remote/comp filters.
        assert!(query.get("workplace_types_or").is_none());
        assert!(query.get("min_salary_usd").is_none());
        // No watermark.
        assert!(query.get("discovered_at_gte").is_none());
    }

    #[test]
    fn strict_query_adds_remote_and_comp_filters() {
        let mut source = source_config("k");
        source.strict_filtering = true;
        let adapter = Theirstack::new(&source, &config(), None).unwrap();
        let query = adapter.build_query();
        assert_eq!(query["workplace_types_or"], json!(["remote"]));
        assert_eq!(query["min_salary_usd"], json!(180_000));
    }

    #[test]
    fn query_includes_watermark_when_provided() {
        let adapter = Theirstack::new(
            &source_config("k"),
            &config(),
            Some("2024-01-01T00:00:00Z".into()),
        )
        .unwrap();
        assert_eq!(
            adapter.build_query()["discovered_at_gte"],
            json!("2024-01-01T00:00:00Z")
        );
    }

    #[test]
    fn skills_never_shape_the_query() {
        let query = adapter("k").build_query();
        assert!(query.get("job_technology_slug_or").is_none());
        assert!(query.get("job_technology_slug_and").is_none());
    }

    // ── parsing (task 2.2) ───────────────────────────────────────

    #[test]
    fn parses_fixture_fields() {
        let value = serde_json::json!({
            "data": [fixture_job()],
            "metadata": {"truncated_results": 0}
        });
        let response = Theirstack::parse_response(&value).unwrap();
        assert_eq!(response.jobs.len(), 1);
        let job = &response.jobs[0];
        assert_eq!(job.title.as_deref(), Some("Senior Data Engineer"));
        assert_eq!(job.company.as_deref(), Some("Acme"));
        assert_eq!(job.remote, Some(true));
        assert_eq!(job.technology_slugs, vec!["postgresql", "kafka"]);
        assert_eq!(job.url.as_deref(), Some("https://acme.com/careers/job/123"));
        let comp = job.comp.as_ref().unwrap();
        assert_eq!(comp.min, Some(200_000));
        assert_eq!(comp.max, Some(250_000));
        assert!(job.description.contains("Senior Data Engineer"));
    }

    #[test]
    fn parse_comp_ignores_non_usd_salary() {
        // v0 has no currency conversion, and the gate contract is USD/year:
        // a non-USD-only salary must map to None (unknown), not feed a GBP
        // amount into the USD floor and false-reject the posting.
        let record = serde_json::json!({
            "min_annual_salary": 150000,
            "max_annual_salary": 200000,
            "salary_currency": "GBP"
        });
        assert!(parse_comp(&record).is_none());
    }

    #[test]
    fn parse_comp_uses_usd_fields_with_usd_currency() {
        // The `_usd` fields win and the range is labeled USD, regardless of
        // the posting's original currency.
        let record = serde_json::json!({
            "min_annual_salary_usd": 180000,
            "max_annual_salary_usd": 220000,
            "salary_currency": "GBP",
            "salary_string": "£150,000"
        });
        let comp = parse_comp(&record).unwrap();
        assert_eq!(comp.min, Some(180_000));
        assert_eq!(comp.max, Some(220_000));
        assert_eq!(comp.currency, "USD");
    }

    #[test]
    fn parses_truncated_results() {
        let value = serde_json::json!({
            "data": [],
            "metadata": {"truncated_results": 7}
        });
        let response = Theirstack::parse_response(&value).unwrap();
        assert_eq!(response.truncated_results, 7);
    }

    #[test]
    fn missing_data_array_errors() {
        assert!(Theirstack::parse_response(&serde_json::json!({})).is_err());
    }

    // ── mapping to IngestOutcome (task 2.3) ───────────────────────

    #[test]
    fn fixture_maps_to_expected_outcome() {
        let value = serde_json::json!({ "data": [fixture_job()] });
        let response = Theirstack::parse_response(&value).unwrap();
        let outcome = response.jobs.into_iter().next().unwrap().into_outcome();
        assert_eq!(outcome.adapter, "theirstack");
        assert_eq!(outcome.source, "theirstack");
        assert_eq!(
            outcome.url.as_deref(),
            Some("https://acme.com/careers/job/123")
        );
        assert!(outcome.raw_text.contains("Senior Data Engineer"));
        assert_eq!(
            outcome.extracted.title.as_deref(),
            Some("Senior Data Engineer")
        );
        assert_eq!(outcome.extracted.company.as_deref(), Some("Acme"));
        assert_eq!(outcome.extracted.remote, Some(true));
        assert_eq!(outcome.extracted.comp.unwrap().min, Some(200_000));
    }

    #[tokio::test]
    async fn missing_key_returns_err() {
        let adapter = adapter("");
        let client = crate::ingest::default_client().unwrap();
        let result = adapter.fetch(&client).await;
        assert!(result.is_err());
    }

    // ── trust-but-verify (task 2.5) ──────────────────────────────

    fn ours_for(job: &TheirstackJob) -> ExtractedFields {
        ingest::extract::extract_fields(&job.description, job.location.as_deref())
    }

    #[test]
    fn mismatch_detects_salary_disagreement() {
        // Structured comp is $200k-$250k; the description quotes a
        // different range, so our heuristics disagree.
        let mut job = parse_job(&fixture_job());
        job.description = "Salary: $300,000 - $350,000. Remote.".into();
        let ours = ours_for(&job);
        assert!(mismatches(&job, &ours).contains(&MismatchField::Comp));
    }

    #[test]
    fn no_mismatch_when_fields_agree() {
        let job = parse_job(&fixture_job());
        // The fixture's description quotes $200k-$250k and "Remote", matching
        // the structured fields.
        let ours = ours_for(&job);
        assert!(mismatches(&job, &ours).is_empty());
    }

    #[test]
    fn comp_mismatch_ignores_raw_formatting() {
        // Numerics/currency/period agree; only `raw` differs (our regex
        // capture "$200k - $250k" vs TheirStack's "salary_string"). This must
        // NOT fire a comp mismatch — `raw` is a presentation string from two
        // independent sources, and comparing it made every comp-carrying
        // posting a phantom mismatch (the over-firing Remi flagged).
        let mut job = parse_job(&fixture_job());
        job.description = "Salary: $200k - $250k. Remote.".into();
        let ours = ours_for(&job);
        // Sanity: the numbers agree, the raw strings differ.
        let o = ours.comp.as_ref().unwrap();
        let j = job.comp.as_ref().unwrap();
        assert_eq!(o.min, j.min);
        assert_eq!(o.max, j.max);
        assert_ne!(o.raw, j.raw);
        assert!(!mismatches(&job, &ours).contains(&MismatchField::Comp));
    }

    #[test]
    fn mismatch_detects_missing_structured_salary_quoted_in_description() {
        // The reverse direction: TheirStack omits the structured salary but
        // the description quotes one — ingest would store unknown comp while
        // discarding extractable data. This must surface, not be suppressed.
        let mut job = parse_job(&fixture_job());
        job.comp = None;
        job.description = "Salary: $200,000 - $250,000. Remote.".into();
        let ours = ours_for(&job);
        assert!(mismatches(&job, &ours).contains(&MismatchField::Comp));
    }

    #[test]
    fn mismatch_detects_missing_structured_remote_quoted_in_description() {
        let mut job = parse_job(&fixture_job());
        job.remote = None;
        job.description = "Salary: $200,000 - $250,000. Remote.".into();
        let ours = ours_for(&job);
        assert!(mismatches(&job, &ours).contains(&MismatchField::Remote));
    }

    // ── mismatch span fields (design decision 2) ────────────────

    /// A minimal tracing `Layer` that captures every recorded span field as
    /// `(name, debug-value)`, so tests can assert what a span carried
    /// (mirrors the pattern in `commands/mark.rs`).
    struct CapturingLayer {
        fields: Arc<Mutex<Vec<(String, String)>>>,
    }

    struct CaptureVisitor<'a> {
        out: &'a mut Vec<(String, String)>,
    }

    impl tracing::field::Visit for CaptureVisitor<'_> {
        fn record_debug(&mut self, field: &tracing::field::Field, value: &dyn std::fmt::Debug) {
            self.out
                .push((field.name().to_string(), format!("{value:?}")));
        }
    }

    impl<S: tracing::Subscriber> tracing_subscriber::layer::Layer<S> for CapturingLayer {
        fn on_record(
            &self,
            _id: &tracing::span::Id,
            values: &tracing::span::Record<'_>,
            _ctx: tracing_subscriber::layer::Context<'_, S>,
        ) {
            let mut out = Vec::new();
            let mut visitor = CaptureVisitor { out: &mut out };
            values.record(&mut visitor);
            self.fields.lock().unwrap().extend(out);
        }
    }

    #[test]
    fn mismatch_emits_span_fields_with_values() {
        let mut job = parse_job(&fixture_job());
        // Structured comp is $200k-$250k; the description quotes $300k-$350k.
        job.description = "Salary: $300,000 - $350,000. Remote.".into();

        let captured = Arc::new(Mutex::new(Vec::new()));
        let layer = CapturingLayer {
            fields: captured.clone(),
        };
        let subscriber = tracing_subscriber::registry().with(layer);
        tracing::subscriber::with_default(subscriber, || {
            emit_mismatches(&job);
        });

        let fields = captured.lock().unwrap();
        let value_of = |name: &str| {
            fields
                .iter()
                .find(|(n, _)| n == name)
                .map(|(_, v)| v.clone())
                .unwrap_or_else(|| panic!("span field {name} not recorded"))
        };
        let structured = value_of("comp_structured");
        let extracted = value_of("comp_extracted");
        // Structured carries TheirStack's $200k-$250k, extracted carries our
        // $300k-$350k — the two sides are queryable and distinguishable.
        assert!(structured.contains("200000"));
        assert!(extracted.contains("300000"));
        assert_ne!(structured, extracted);
    }

    // ── property tests: comp_disagrees (proptest) ───────────────

    fn arb_comp_range() -> impl Strategy<Value = CompRange> {
        (
            any::<Option<u64>>(),
            any::<Option<u64>>(),
            any::<String>(),
            any::<String>(),
            any::<String>(),
        )
            .prop_map(|(min, max, currency, period, raw)| CompRange {
                min,
                max,
                currency,
                period,
                raw,
            })
    }

    proptest! {
        #[test]
        fn comp_disagrees_equals_semantic_field_diff(
            a in arb_comp_range(),
            b in arb_comp_range(),
        ) {
            let expected = a.min != b.min
                || a.max != b.max
                || a.currency != b.currency
                || a.period != b.period;
            prop_assert_eq!(comp_disagrees(Some(&a), Some(&b)), expected);
        }

        #[test]
        fn comp_disagrees_ignores_raw(
            base in arb_comp_range(),
            raw_a in any::<String>(),
            raw_b in any::<String>(),
        ) {
            let mut a = base.clone();
            a.raw = raw_a;
            let mut b = base;
            b.raw = raw_b;
            prop_assert!(!comp_disagrees(Some(&a), Some(&b)));
        }

        #[test]
        fn comp_disagrees_is_symmetric(
            a in arb_comp_range(),
            b in arb_comp_range(),
        ) {
            prop_assert_eq!(
                comp_disagrees(Some(&a), Some(&b)),
                comp_disagrees(Some(&b), Some(&a)),
            );
        }

        #[test]
        fn comp_disagrees_none_semantics(x in arb_comp_range()) {
            prop_assert!(!comp_disagrees(None, None));
            prop_assert!(comp_disagrees(Some(&x), None));
            prop_assert!(comp_disagrees(None, Some(&x)));
        }
    }

    // ── watermark normalization ──────────────────────────────────

    #[test]
    fn normalizes_naive_discovered_at_to_utc() {
        assert_eq!(
            normalize_discovered_at("2024-01-01T00:00:00"),
            "2024-01-01T00:00:00Z"
        );
        assert_eq!(
            normalize_discovered_at("2024-01-01T00:00:00Z"),
            "2024-01-01T00:00:00Z"
        );
    }

    #[test]
    fn normalizes_explicit_offsets_to_utc() {
        // An offset like `-05:00` must not be blindly `Z`-appended (the bug
        // this replaces): it parses as an instant and renders in Zulu time.
        assert_eq!(
            normalize_discovered_at("2024-01-01T00:00:00+02:00"),
            "2023-12-31T22:00:00Z"
        );
        assert_eq!(
            normalize_discovered_at("2024-01-01T00:00:00-05:00"),
            "2024-01-01T05:00:00Z"
        );
    }

    #[test]
    fn normalizes_fractional_seconds_to_uniform_precision() {
        // Truncating to whole seconds keeps the watermark lexicographically
        // sortable regardless of the API's sub-second precision.
        assert_eq!(
            normalize_discovered_at("2024-01-01T00:00:00.123Z"),
            "2024-01-01T00:00:00Z"
        );
    }

    #[test]
    fn max_discovered_at_takes_latest() {
        let jobs = vec![
            TheirstackJob {
                discovered_at: Some("2024-01-01T00:00:00".into()),
                ..default_job()
            },
            TheirstackJob {
                discovered_at: Some("2024-01-02T00:00:00".into()),
                ..default_job()
            },
        ];
        assert_eq!(
            max_discovered_at(&jobs).as_deref(),
            Some("2024-01-02T00:00:00Z")
        );
    }

    fn default_job() -> TheirstackJob {
        TheirstackJob {
            url: None,
            description: String::new(),
            title: None,
            company: None,
            location: None,
            comp: None,
            remote: None,
            technology_slugs: vec![],
            discovered_at: None,
        }
    }

    // ── fetch_jobs transport (review: pagination was untested) ──

    /// A captured POST: the serialized JSON body and optional bearer token.
    type CapturedRequest = (String, Option<String>);

    /// A scripted POST response: HTTP status plus the JSON body.
    type ScriptedResponse = (u16, Value);

    struct ScriptedFetcher {
        responses: Arc<Mutex<VecDeque<ScriptedResponse>>>,
        /// Scripted credit-balance GET responses, in call order (per page —
        /// the budget loop checks the balance before each page). An empty
        /// queue fails the check, exercising the warn-and-proceed-uncapped
        /// fallback.
        balance_responses: Arc<Mutex<VecDeque<ScriptedResponse>>>,
        requests: Arc<Mutex<Vec<CapturedRequest>>>,
    }

    impl ScriptedFetcher {
        /// ScriptedFetcher with no balance checks scripted (uncapped pages).
        fn new(
            responses: impl IntoIterator<Item = ScriptedResponse>,
        ) -> (Self, Arc<Mutex<Vec<CapturedRequest>>>) {
            let requests = Arc::new(Mutex::new(Vec::new()));
            (
                Self {
                    responses: Arc::new(Mutex::new(responses.into_iter().collect())),
                    balance_responses: Arc::new(Mutex::new(VecDeque::new())),
                    requests: requests.clone(),
                },
                requests,
            )
        }

        /// A live-shape balance response: total minus used = remaining.
        fn balance(total: u64, used: u64) -> ScriptedResponse {
            (
                200,
                serde_json::json!({
                    "ui_credits": 50,
                    "used_ui_credits": 0,
                    "api_credits": total,
                    "used_api_credits": used,
                    "earliest_expiration": "2026-10-25T14:40:09.456468Z"
                }),
            )
        }
    }

    impl Fetcher for ScriptedFetcher {
        async fn get(&self, _url: &Url) -> Result<FetchResponse> {
            Err(miette::miette!("get not scripted"))
        }

        async fn get_bearer(&self, _url: &Url, _bearer: Option<String>) -> Result<FetchResponse> {
            let (status, value) = self
                .balance_responses
                .lock()
                .unwrap()
                .pop_front()
                .ok_or_else(|| miette::miette!("balance response not scripted"))?;
            Ok(FetchResponse {
                status,
                retry_after: None,
                final_url: None,
                body: serde_json::to_string(&value).unwrap(),
            })
        }

        async fn post(
            &self,
            _url: &Url,
            body: String,
            bearer: Option<String>,
        ) -> Result<FetchResponse> {
            self.requests.lock().unwrap().push((body, bearer));
            let (status, value) = self
                .responses
                .lock()
                .unwrap()
                .pop_front()
                .ok_or_else(|| miette::miette!("scripted fetcher ran out of responses"))?;
            Ok(FetchResponse {
                status,
                retry_after: None,
                final_url: None,
                body: serde_json::to_string(&value).unwrap(),
            })
        }
    }

    #[tokio::test(start_paused = true)]
    async fn fetch_jobs_paginates_and_propagates_bearer() {
        fn job(url: &str) -> Value {
            serde_json::json!({
                "job_title": "Engineer",
                "description": "Remote job.",
                "final_url": url,
                "discovered_at": "2024-01-01T00:00:00"
            })
        }
        // Page 0: a full page; page 1: a short final page carrying the
        // truncation count. The loop must terminate on the short page and
        // take the max truncation across pages.
        let page0 = serde_json::json!({
            "data": (0..PAGE_SIZE as usize)
                .map(|i| job(&format!("https://example.com/job/{i}")))
                .collect::<Vec<_>>(),
            "metadata": {"truncated_results": 0}
        });
        let page1 = serde_json::json!({
            "data": [job("https://example.com/job/500")],
            "metadata": {"truncated_results": 5}
        });
        let (fetcher, requests) = ScriptedFetcher::new([(200, page0), (200, page1)]);
        let client = PoliteClient::new(fetcher);
        let url = Url::parse(THEIRSTACK_API).unwrap();
        let balance_url = Url::parse(THEIRSTACK_BALANCE_API).unwrap();
        let query = serde_json::json!({"posted_at_max_age_days": 30, "limit": PAGE_SIZE});

        // No balance responses scripted: the check fails, the fetch proceeds
        // uncapped (the 402 salvage is the backstop).
        let fetched = fetch_jobs(&client, &url, &query, "secret", &balance_url, None)
            .await
            .unwrap();

        assert_eq!(fetched.jobs.len(), 501);
        assert_eq!(fetched.truncated_results, 5);
        assert_eq!(fetched.partial_error, None);
        assert_eq!(fetched.credits_spent, 501);

        let reqs = requests.lock().unwrap();
        assert_eq!(reqs.len(), 2);
        // The page cursor starts at 0 and increments; bearer propagates.
        assert!(reqs[0].0.contains("\"page\":0"));
        assert!(reqs[1].0.contains("\"page\":1"));
        assert_eq!(reqs[0].1.as_deref(), Some("secret"));
        assert_eq!(reqs[1].1.as_deref(), Some("secret"));
    }

    // ── mid-pagination salvage (design decision 8) ────────────

    /// TheirStack's live 402 body (E-007, observed 2026-10-07): the
    /// "Required: N API credits" clause is the unreturned-record count.
    fn credit_402_body(required: u64, available: u64) -> Value {
        serde_json::json!({
            "request_id": 58596504,
            "error": {
                "code": "E-007",
                "title": "Not enough credits to perform this action",
                "description": format!(
                    "You need to upgrade your plan to perform this action. \
                     Required: {required} API credits. You currently have \
                     {available} API credits. You need {required} more API credits."
                )
            }
        })
    }

    #[tokio::test(start_paused = true)]
    async fn mid_pagination_402_salvages_fetched_jobs() {
        // The live incident: page 0 returns a full paid page, page 1 hits
        // 402 with 199 credits left and 301 still required. The fetched
        // records must survive (they are paid for), the unreturned count
        // must surface as truncation, and the reason must carry the error.
        fn job(i: usize) -> Value {
            serde_json::json!({
                "job_title": "Engineer",
                "description": "Remote job.",
                "final_url": format!("https://example.com/job/{i}"),
                "discovered_at": "2024-01-01T00:00:00"
            })
        }
        let page0 = serde_json::json!({
            "data": (0..PAGE_SIZE as usize).map(job).collect::<Vec<_>>(),
            "metadata": {"truncated_results": 0}
        });
        let (fetcher, _requests) =
            ScriptedFetcher::new([(200, page0), (402, credit_402_body(301, 199))]);
        let client = PoliteClient::new(fetcher);
        let url = Url::parse(THEIRSTACK_API).unwrap();
        let balance_url = Url::parse(THEIRSTACK_BALANCE_API).unwrap();
        let query = serde_json::json!({"posted_at_max_age_days": 30, "limit": PAGE_SIZE});

        let fetched = fetch_jobs(&client, &url, &query, "secret", &balance_url, None)
            .await
            .unwrap();

        assert_eq!(fetched.jobs.len(), PAGE_SIZE as usize);
        assert_eq!(fetched.truncated_results, 301);
        let reason = fetched
            .partial_error
            .expect("partial fetch carries its reason");
        assert!(reason.contains("status 402"), "reason: {reason}");
        assert!(
            reason.contains("Required: 301 API credits"),
            "reason: {reason}"
        );
    }

    #[tokio::test(start_paused = true)]
    async fn page_zero_402_reports_exhaustion_without_losing_the_count() {
        // The whole-source failure contract covers *fetch* failures; a
        // payment-required response on page 0 is a known exhaustion signal,
        // so its unreturned count must survive (PR #44 review: the old
        // page-0 bail! discarded it). No records were paid for — the batch
        // is empty — but the source still reports as failed with the
        // reason, and the count lands as truncation.
        let (fetcher, _requests) = ScriptedFetcher::new([(402, credit_402_body(500, 199))]);
        let client = PoliteClient::new(fetcher);
        let url = Url::parse(THEIRSTACK_API).unwrap();
        let balance_url = Url::parse(THEIRSTACK_BALANCE_API).unwrap();
        let query = serde_json::json!({"posted_at_max_age_days": 30, "limit": PAGE_SIZE});

        let fetched = fetch_jobs(&client, &url, &query, "secret", &balance_url, None)
            .await
            .expect("a page-0 402 is exhaustion, not a hard failure");

        assert!(fetched.jobs.is_empty());
        assert_eq!(fetched.truncated_results, 500);
        let reason = fetched.partial_error.expect("reason carried");
        assert!(reason.contains("status 402"), "reason: {reason}");
        assert!(
            reason.contains("Required: 500 API credits"),
            "reason: {reason}"
        );
    }

    #[test]
    fn unreturned_count_parses_the_live_402_body() {
        let body = credit_402_body(301, 199);
        assert_eq!(unreturned_from_402(Some(&body)), 301);
    }

    #[test]
    fn unreturned_count_is_best_effort_on_unknown_shapes() {
        // Shape drift or a non-JSON body yields 0 — the reason string, not
        // the count, is the contract that must always hold.
        assert_eq!(unreturned_from_402(None), 0);
        assert_eq!(
            unreturned_from_402(Some(&serde_json::json!({"error": {}}))),
            0
        );
        assert_eq!(
            unreturned_from_402(Some(&serde_json::json!({
                "error": {"description": "something else entirely"}
            }))),
            0
        );
    }

    // ── query-table shaping (`theirstack-spend-control` decision 1) ──

    fn toml_query(text: &str) -> BTreeMap<String, toml::Value> {
        toml::from_str(text).expect("test query table parses")
    }

    fn source_with_query(query: Option<BTreeMap<String, toml::Value>>) -> SourceConfig {
        SourceConfig {
            enabled: true,
            api_key: "k".into(),
            query,
            ..Default::default()
        }
    }

    #[test]
    fn operator_query_rides_along_the_generated_params() {
        let source = source_with_query(Some(toml_query(
            "job_seniority_or = [\"senior\", \"staff\"]\njob_technology_slug_or = [\"kubernetes\"]\njob_country_code_or = [\"US\", \"CA\"]",
        )));
        let adapter = Theirstack::new(&source, &config(), None).unwrap();
        let query = adapter.build_query();

        // Generated params still present.
        assert_eq!(query["posted_at_max_age_days"], 30);
        assert_eq!(query["limit"], PAGE_SIZE);
        assert_eq!(query["company_domain_not"], json!(["google.com"]));
        assert_eq!(query["company_name_not"], json!(["salesforce"]));
        // Operator filters ride along.
        assert_eq!(query["job_seniority_or"], json!(["senior", "staff"]));
        assert_eq!(query["job_technology_slug_or"], json!(["kubernetes"]));
        assert_eq!(query["job_country_code_or"], json!(["US", "CA"]));
    }

    #[test]
    fn always_reserved_query_keys_are_rejected() {
        // These keys are the adapter's budgeting machinery — a table entry
        // would silently break pagination, recency, the cursor, or the
        // blacklist pre-filter, so construction fails before any I/O.
        for key in ALWAYS_RESERVED_QUERY_KEYS {
            let table = format!("{key} = 1");
            let source = source_with_query(Some(toml_query(&table)));
            let err = Theirstack::new(&source, &config(), None)
                .err()
                .expect("reserved key must fail construction");
            assert!(
                err.to_string().contains(key),
                "error names the reserved key {key}: {err}"
            );
        }
    }

    #[test]
    fn strict_gate_keys_are_reserved_only_in_strict_mode() {
        for key in STRICT_RESERVED_QUERY_KEYS {
            // Strict mode on: the table collides with the generated gate.
            let mut strict = source_with_query(Some(toml_query(&format!("{key} = [\"x\"]"))));
            strict.strict_filtering = true;
            assert!(
                Theirstack::new(&strict, &config(), None).is_err(),
                "{key} must be reserved under strict_filtering"
            );

            // Strict mode off: free operator surface — e.g.
            // workplace_types_or = ["remote", "hybrid"], a shape strict
            // mode cannot express.
            let free = source_with_query(Some(toml_query(&format!(
                "{key} = [\"remote\", \"hybrid\"]"
            ))));
            let adapter = Theirstack::new(&free, &config(), None)
                .expect("non-strict mode must accept the key");
            assert_eq!(adapter.build_query()[key], json!(["remote", "hybrid"]));
        }
    }

    // ── budget-aware pagination (`theirstack-spend-control` decision 2) ──

    fn jobs_page(count: u64) -> Value {
        serde_json::json!({
            "data": (0..count)
                .map(|i| serde_json::json!({
                    "job_title": "Engineer",
                    "description": "Remote job.",
                    "final_url": format!("https://example.com/job/{i}"),
                    "discovered_at": "2024-01-01T00:00:00"
                }))
                .collect::<Vec<_>>(),
            "metadata": {"truncated_results": 0}
        })
    }

    #[tokio::test(start_paused = true)]
    async fn balance_caps_the_page_limit_and_stops_when_exhausted() {
        // 199 credits remaining (the live post-incident balance): the page
        // request is capped to 199, the full capped page continues, and the
        // next balance check (0 remaining) does NOT blindly declare
        // exhaustion — the adapter asks once more, free either way, and the
        // API's own payment-required response settles it: records already
        // paid for are kept, and the 402's count is the lower bound on the
        // unreturned tail (the false-partial fix).
        let (mut fetcher, requests) =
            ScriptedFetcher::new([(200, jobs_page(199)), (402, credit_402_body(500, 0))]);
        fetcher.balance_responses = Arc::new(Mutex::new(VecDeque::from([
            ScriptedFetcher::balance(1700, 1501),
            ScriptedFetcher::balance(0, 0),
        ])));
        let client = PoliteClient::new(fetcher);
        let url = Url::parse(THEIRSTACK_API).unwrap();
        let balance_url = Url::parse(THEIRSTACK_BALANCE_API).unwrap();
        let query = serde_json::json!({"posted_at_max_age_days": 30});

        let fetched = fetch_jobs(&client, &url, &query, "secret", &balance_url, None)
            .await
            .unwrap();

        assert_eq!(fetched.jobs.len(), 199);
        assert_eq!(fetched.credits_spent, 199);
        assert_eq!(fetched.truncated_results, 500);
        let reason = fetched
            .partial_error
            .expect("balance exhaustion stops as a partial fetch");
        assert!(reason.contains("status 402"), "reason: {reason}");
        assert!(
            reason.contains("Required: 500 API credits"),
            "reason: {reason}"
        );

        let reqs = requests.lock().unwrap();
        assert_eq!(
            reqs.len(),
            2,
            "one capped page plus the free zero-balance arbitration ask"
        );
        assert!(
            reqs[0].0.contains("\"limit\":199"),
            "page limit capped to the balance: {}",
            reqs[0].0
        );
        assert!(
            reqs[1].0.contains("\"limit\":500"),
            "the zero-balance ask is uncapped — the API arbitrates: {}",
            reqs[1].0
        );
    }

    #[tokio::test(start_paused = true)]
    async fn zero_balance_mid_run_completes_cleanly_when_nothing_remains() {
        // The false-partial bug (caught by the budget-loop proptest): the
        // balance cap made the last page fetch EXACTLY the final records,
        // the next balance check saw 0, and a COMPLETE fetch was reported
        // as failed ("credit balance exhausted"). The fix: ask once more —
        // with nothing left to return, the empty page completes the fetch
        // cleanly and no failure is reported at all.
        let (mut fetcher, _requests) =
            ScriptedFetcher::new([(200, jobs_page(500)), (200, jobs_page(0))]);
        fetcher.balance_responses = Arc::new(Mutex::new(VecDeque::from([
            ScriptedFetcher::balance(1000, 0),
            ScriptedFetcher::balance(1000, 500),
        ])));
        let client = PoliteClient::new(fetcher);
        let url = Url::parse(THEIRSTACK_API).unwrap();
        let balance_url = Url::parse(THEIRSTACK_BALANCE_API).unwrap();
        let query = serde_json::json!({"posted_at_max_age_days": 30});

        let fetched = fetch_jobs(&client, &url, &query, "secret", &balance_url, None)
            .await
            .unwrap();

        // 500 matches, 500 credits: page 0 (limit 500) fetched them all;
        // the ask after the balance hit 0 returned an empty page — complete,
        // no failure, nothing truncated.
        assert_eq!(fetched.jobs.len(), 500);
        assert_eq!(fetched.credits_spent, 500);
        assert_eq!(fetched.truncated_results, 0);
        assert_eq!(fetched.partial_error, None);
    }

    #[tokio::test(start_paused = true)]
    async fn per_run_budget_bounds_spend() {
        // A declared budget of 400 caps the page to 400; the full page
        // continues and the next iteration stops at the budget with a
        // reason — no further page requests. The fixtures model the real
        // account arithmetic (1699 remaining after the top-up; 1299 after
        // the 400-record spend) — the scripted response never exceeds what
        // the balance and budget can actually pay for (PR #45 review: the
        // old fixtures scripted 199 credits against a 400-record page).
        let (mut fetcher, requests) = ScriptedFetcher::new([(200, jobs_page(400))]);
        fetcher.balance_responses = Arc::new(Mutex::new(VecDeque::from([
            ScriptedFetcher::balance(3200, 1501),
            ScriptedFetcher::balance(3200, 1901),
        ])));
        let client = PoliteClient::new(fetcher);
        let url = Url::parse(THEIRSTACK_API).unwrap();
        let balance_url = Url::parse(THEIRSTACK_BALANCE_API).unwrap();
        let query = serde_json::json!({"posted_at_max_age_days": 30});

        let fetched = fetch_jobs(&client, &url, &query, "secret", &balance_url, Some(400))
            .await
            .unwrap();

        assert_eq!(fetched.jobs.len(), 400);
        assert_eq!(fetched.credits_spent, 400);
        let reason = fetched
            .partial_error
            .expect("budget stop is a partial fetch");
        assert!(
            reason.contains("per-run credit budget of 400 reached"),
            "reason: {reason}"
        );
        assert_eq!(requests.lock().unwrap().len(), 1);
    }

    #[tokio::test(start_paused = true)]
    async fn zero_balance_before_anything_fails_the_whole_source() {
        // Nothing fetched yet: the whole-source failure contract (spec:
        // no records, source reported failed, run continues).
        let (mut fetcher, requests) = ScriptedFetcher::new([(200, jobs_page(10))]);
        fetcher.balance_responses =
            Arc::new(Mutex::new(VecDeque::from([ScriptedFetcher::balance(0, 0)])));
        let client = PoliteClient::new(fetcher);
        let url = Url::parse(THEIRSTACK_API).unwrap();
        let balance_url = Url::parse(THEIRSTACK_BALANCE_API).unwrap();
        let query = serde_json::json!({"posted_at_max_age_days": 30});

        let err = fetch_jobs(&client, &url, &query, "secret", &balance_url, None)
            .await
            .expect_err("zero balance must fail the source before fetching");
        assert!(
            err.to_string().contains("credit balance exhausted"),
            "message: {err}"
        );
        assert!(requests.lock().unwrap().is_empty(), "no page request made");
    }

    // ── budget loop model check (proptest; PR #45 review finding 4) ──

    /// A model of TheirStack's search API and credit accounting, honoring
    /// the live-verified request contract: a page request returns
    /// `min(limit, remaining matches)` records, charges one credit per
    /// record, and — the assertion this model exists for — the adapter
    /// must never ask for more than the remaining balance (or the
    /// remaining budget) can pay for. The response is derived FROM the
    /// request, so a fixture that lies about the API (the failure mode
    /// this guards: a scripted 400-record page against a 199-credit
    /// balance the real API would refuse) is impossible by construction.
    #[derive(Default)]
    struct ModelState {
        used_credits: u64,
        served: u64,
        requested_limits: Vec<u64>,
        violations: Vec<String>,
    }

    struct ModelApi {
        total_credits: u64,
        matches: u64,
        budget: Option<u64>,
        state: Arc<Mutex<ModelState>>,
    }

    impl Fetcher for ModelApi {
        async fn get(&self, _url: &Url) -> Result<FetchResponse> {
            Err(miette::miette!("model: plain get not expected"))
        }

        async fn get_bearer(&self, _url: &Url, _bearer: Option<String>) -> Result<FetchResponse> {
            let used = self.state.lock().unwrap().used_credits;
            Ok(FetchResponse {
                status: 200,
                retry_after: None,
                final_url: None,
                body: serde_json::json!({
                    "ui_credits": 50,
                    "used_ui_credits": 0,
                    "api_credits": self.total_credits,
                    "used_api_credits": used,
                })
                .to_string(),
            })
        }

        async fn post(
            &self,
            _url: &Url,
            body: String,
            _bearer: Option<String>,
        ) -> Result<FetchResponse> {
            let mut state = self.state.lock().unwrap();
            let request: Value = serde_json::from_str(&body).expect("model request parses");
            let limit = request
                .get("limit")
                .and_then(Value::as_u64)
                .expect("adapter always sends limit");
            let remaining = self.total_credits - state.used_credits;
            let budget_left = self.budget.map(|b| b.saturating_sub(state.used_credits));
            // The good-citizen contract: never request more than payable —
            // EXCEPT at a zero balance, where the adapter deliberately asks
            // uncapped (free either way) so the API — not the adapter —
            // arbitrates whether anything actually remains unfetched (the
            // false-partial bug: a complete fetch reported as exhausted).
            if remaining > 0 && limit > remaining {
                state.violations.push(format!(
                    "requested {limit} records with {remaining} credits"
                ));
            }
            if let Some(left) = budget_left
                && limit > left
            {
                state
                    .violations
                    .push(format!("requested {limit} records with budget {left} left"));
            }
            state.requested_limits.push(limit);
            let matches_left = self.matches - state.served;
            let count = limit.min(matches_left);
            // The live-verified demand contract (GWLJ-2yflze): a request
            // requires credits >= min(limit, remaining matches) — fewer,
            // and the API refuses with a payment-required 402, charging
            // nothing. The model must refuse like the real API does.
            if count > remaining {
                return Ok(FetchResponse {
                    status: 402,
                    retry_after: None,
                    final_url: None,
                    body: serde_json::json!({
                        "request_id": 1,
                        "error": {
                            "code": "E-007",
                            "title": "Not enough credits to perform this action",
                            "description": format!(
                                "You need to upgrade your plan to perform this \
                                 action. Required: {count} API credits. You \
                                 currently have {remaining} API credits."
                            ),
                        },
                    })
                    .to_string(),
                });
            }
            let first_index = state.served;
            state.used_credits += count;
            state.served += count;
            let jobs: Vec<Value> = (0..count)
                .map(|i| {
                    serde_json::json!({
                        "job_title": "Engineer",
                        "description": "Remote job.",
                        "final_url": format!("https://example.com/job/{}", first_index + i),
                        "discovered_at": "2024-01-01T00:00:00",
                    })
                })
                .collect();
            Ok(FetchResponse {
                status: 200,
                retry_after: None,
                final_url: None,
                body: serde_json::json!({
                    "data": jobs,
                    "metadata": {"truncated_results": 0},
                })
                .to_string(),
            })
        }
    }

    proptest! {
        /// Whatever the balance, budget, and match count, the budget loop
        /// spends exactly min(matches, remaining, budget) — never requests
        /// an unpayable page (checked inside the model), never overspends,
        /// and reports a partial fetch with the right stop reason iff
        /// matches remain unfetched.
        #[test]
        fn budget_loop_spends_within_bounds(
            remaining in 0u64..1200,
            budget in proptest::option::of(0u64..1200),
            matches in 0u64..1200,
        ) {
            let state = Arc::new(Mutex::new(ModelState::default()));
            let model = ModelApi {
                total_credits: remaining,
                matches,
                budget,
                state: state.clone(),
            };
            let client =
                PoliteClient::with_delays(std::time::Duration::ZERO, std::time::Duration::from_secs(30), model);
            let url = Url::parse(THEIRSTACK_API).unwrap();
            let balance_url = Url::parse(THEIRSTACK_BALANCE_API).unwrap();
            let query = serde_json::json!({"posted_at_max_age_days": 30});

            let rt = tokio::runtime::Builder::new_current_thread()
                .enable_all()
                .build()
                .unwrap();
            let result = rt
                .block_on(fetch_jobs(&client, &url, &query, "secret", &balance_url, budget));

            let model_state = state.lock().unwrap();
            prop_assert!(
                model_state.violations.is_empty(),
                "unpayable page requests: {:?}",
                model_state.violations
            );

            if remaining == 0 || budget == Some(0) {
                // Nothing payable before any record was fetched: the
                // whole-source failure contract, and no page request.
                let err = result.expect_err("nothing payable must Err");
                let message = err.to_string();
                if remaining == 0 {
                    prop_assert!(message.contains("credit balance exhausted"), "{message}");
                } else {
                    prop_assert!(message.contains("per-run credit budget"), "{message}");
                }
                prop_assert!(model_state.requested_limits.is_empty());
            } else {
                let spent = matches.min(remaining).min(budget.unwrap_or(u64::MAX));
                let fetched = result.expect("payable fetch succeeds");
                prop_assert_eq!(fetched.credits_spent, spent);
                prop_assert_eq!(fetched.jobs.len() as u64, spent);
                if spent == matches {
                    // A fetch that got everything reports no failure —
                    // EXCEPT when the per-run budget cut landed exactly at
                    // the end: an honest internal stop ("budget reached"),
                    // not an API fact (the balance case can now tell the
                    // difference by asking; the budget cannot, without
                    // spending).
                    if budget == Some(spent) {
                        let reason = fetched
                            .partial_error
                            .expect("the budget stop carries its reason");
                        prop_assert!(
                            reason.contains("per-run credit budget"),
                            "{reason}"
                        );
                    } else {
                        prop_assert!(fetched.partial_error.is_none());
                    }
                } else {
                    let tail = matches - spent;
                    let reason = fetched
                        .partial_error
                        .expect("an incomplete fetch carries its reason");
                    if reason.contains("per-run credit budget") {
                        prop_assert_eq!(budget, Some(spent));
                        prop_assert_eq!(fetched.truncated_results, 0);
                    } else {
                        // Balance exhaustion surfaces as the API's own
                        // payment-required response, whose "Required: N"
                        // is a lower bound on the unreturned tail.
                        prop_assert!(reason.contains("status 402"), "{reason}");
                        prop_assert_eq!(remaining, spent);
                        let budget_left =
                            budget.map(|b| b - spent).unwrap_or(u64::MAX);
                        prop_assert_eq!(
                            fetched.truncated_results,
                            PAGE_SIZE.min(tail).min(budget_left)
                        );
                    }
                }
            }
        }
    }
}
